require 'rails_helper'

RSpec.describe Munchie do
  it 'exists' do
    destination = 'Hollywood,FL'
    destination_temperature = CurrentTemperature.new({ lat: 39.7385,
                                                       lon: -104.9849,
                                                       timezone: 'America/Denver',
                                                       timezone_offset: -25_200,
                                                       current: { dt: 1_615_225_245,
                                                                  sunrise: 1_615_209_724,
                                                                  sunset: 1_615_251_567,
                                                                  temp: 51.49,
                                                                  feels_like: 45.7,
                                                                  pressure: 1027,
                                                                  humidity: 34,
                                                                  dew_point: 25,
                                                                  uvi: 3.26,
                                                                  clouds: 100,
                                                                  visibility: 10_000,
                                                                  wind_speed: 2.15,
                                                                  wind_deg: 177,
                                                                  weather: [{ id: 804, main: 'Clouds',
                                                                              description: 'overcast clouds', icon: '04d' }] } })
    restaurant = Restaurant.new({ businesses: [{ id: 'jwalZ-ZJDzwv2ukp29DHMg',
                                                 alias: 'pachamanka-authentic-peruvian-cuisine-hollywood-3',
                                                 name: 'Pachamanka Authentic Peruvian Cuisine',
                                                 image_url: 'https://s3-media3.fl.yelpcdn.com/bphoto/WrQF2IoZUVzPYetwbpV7xA/o.jpg',
                                                 is_closed: false,
                                                 url: 'https://www.yelp.com/biz/pachamanka-authentic-peruvian-cuisine-hollywood-3?adjust_creative=exsKdI4IsMWYS3_DdjaKlg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=exsKdI4IsMWYS3_DdjaKlg',
                                                 review_count: 503,
                                                 categories: [{ alias: 'peruvian', title: 'Peruvian' },
                                                              { alias: 'seafood', title: 'Seafood' }],
                                                 rating: 4.5,
                                                 coordinates: { latitude: 26.01972,
                                                                longitude: -80.1159 },
                                                 transactions: %w[delivery pickup],
                                                 price: '$$',
                                                 location: { address1: '321 Johnson St',
                                                             address2: '',
                                                             address3: '',
                                                             city: 'Hollywood',
                                                             zip_code: '33019',
                                                             country: 'US',
                                                             state: 'FL',
                                                             display_address: ['321 Johnson St',
                                                                               'Hollywood, FL 33019'] },
                                                 phone: '+19549261020',
                                                 display_phone: '(954) 926-1020',
                                                 distance: 6766.11772060313 }],
                                  total: 348,
                                  region: { center: { longitude: -80.1837158203125,
                                                      latitude: 26.019729291096752 } } })
    directions = Direction.new({ route: { hasTollRoad: false,
                                          hasBridge: true,
                                          boundingBox: { lr: { lng: -80.139053, lat: 25.774994 },
                                                         ul: { lng: -80.199677, lat: 26.011757 } },
                                          distance: 19.709,
                                          hasTimedRestriction: false,
                                          hasTunnel: false,
                                          hasHighway: true,
                                          computedWaypoints: [],
                                          routeError: { errorCode: -400, message: '' },
                                          formattedTime: '00:25:45',
                                          sessionId: '60465b35-034b-5f21-02b4-3500-0a439d50b801',
                                          hasAccessRestriction: false,
                                          realTime: 1714,
                                          hasSeasonalClosure: false,
                                          hasCountryCross: false,
                                          fuelUsed: 0.89,
                                          legs: [{ hasTollRoad: false,
                                                   hasBridge: true,
                                                   destNarrative: 'Proceed to HOLLYWOOD, FL.',
                                                   distance: 19.709,
                                                   hasTimedRestriction: false,
                                                   hasTunnel: false }] } })

    munchie = Munchie.new(destination, destination_temperature, restaurant, directions)
    expect(munchie).to be_a(Munchie)
    expect(munchie).to have_attributes(destination_city: destination,
                                       forecast: { summary: destination_temperature.summary,
                                                   temperature: destination_temperature.temperature },
                                       id: nil,
                                       restaurant: { name: restaurant.name,
                                                     address: restaurant.address },
                                       travel_time: directions.travel_time)
  end
end
